# Generated by Django 5.1.3 on 2025-01-30 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_genre_remove_movie_genres_comment_movielist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='uploaded_by',
        ),
    ]
