# Generated by Django 5.1.3 on 2025-02-02 15:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_movie_uploaded_at_remove_movie_uploaded_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movielist',
            name='user',
        ),
        migrations.AddField(
            model_name='movielist',
            name='users',
            field=models.ManyToManyField(related_name='movie_lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
