# Generated by Django 5.1.3 on 2025-02-06 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_movie_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='uploaded_poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters/'),
        ),
    ]
