# Generated by Django 5.1.3 on 2025-02-06 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_movie_uploaded_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='uploaded_poster',
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_uploaded',
            field=models.ImageField(blank=True, null=True, upload_to='movie_posters/'),
        ),
    ]
